---
version: '3.8'

services:

  php:
    build: ./services/php
    container_name: laravel-formation-php
    volumes: [ '..:/var/www/laravel_formation:cached' ]
    depends_on:
      - mysql
    networks:
      - app

  nginx:
    build: ./services/nginx
    ports: [ '80:80' ]
    volumes: [ '..:/var/www/laravel_formation:cached' ]
    depends_on:
      - php
      - mysql
    networks:
      - app

  mysql:
    image: mysql:8.0.28
    container_name: laravel-formation-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    ports:
      - 3306:3306
    volumes:
      - data_mysql:/var/lib/mysql
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: laravel-formation-pma
    environment:
      - PMA_HOST=mysql
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - app

volumes:
  data_mysql:
    name: laravel-formation-volume-database
networks:
  app:
    name: laravel-formation-app
...

